Controllers/AuthorsController.cs
using LIBRARYMVC_TEST.Models;
using Microsoft.AspNetCore.Mvc;

namespace LIBRARYMVC_TEST.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly DbLibraryMvcContext _DBContext;

        public AuthorsController(DbLibraryMvcContext context)
        {
            _DBContext = context;
        }

        public IActionResult Index()
        {
            var authors = _DBContext.Authors.ToList();
            ViewBag.Message = TempData["Message"];

            return View(authors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Author author)
        {
            if (!ModelState.IsValid) return View(author);

            _DBContext.Authors.Add(author);
            _DBContext.SaveChanges();
            TempData["Message"] = "Autor creado con éxito";

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var author = _DBContext.Authors.Find(id);
            if (author == null) return NotFound();

            return View(author);
        }

        [HttpPost]
        public IActionResult Edit(Author author)
        {
            if (!ModelState.IsValid) return View(author);

            _DBContext.Authors.Update(author);
            _DBContext.SaveChanges();
            TempData["Message"] = "Autor editado con éxito";

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var author = _DBContext.Authors.Where(a => a.Id == id).FirstOrDefault();
            if (author == null) return NotFound();

            return View(author);
        }

        [HttpPost]
        public IActionResult Delete(Author author)
        {
            _DBContext.Authors.Remove(author);
            _DBContext.SaveChanges();
            TempData["Message"] = "Autor eliminado con éxito";

            return RedirectToAction("Index");
        }
    }
}

Controllers/BooksController.cs
using LIBRARYMVC_TEST.Models;
using LIBRARYMVC_TEST.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LIBRARYMVC_TEST.Controllers
{
    public class BooksController : Controller
    {
        private readonly DbLibraryMvcContext _DBContext;

        public BooksController(DbLibraryMvcContext context)
        {
            _DBContext = context;
        }

        public IActionResult Index()
        {
            var books = _DBContext.Books.Include(a => a.Author).ToList();
            ViewBag.Message = TempData["Message"];

            return View(books);
        }

        public IActionResult Create()
        {
            BookVM bookVM = new()
            {
                Book = new Book(),
                AuthorList = GetAuthorList()
            };

            return View(bookVM);
        }

        [HttpPost]
        public IActionResult Create(BookVM bookVM)
        {
            if (!ModelState.IsValid)
            {
                bookVM.AuthorList = GetAuthorList();
                return View(bookVM);
            }

            _DBContext.Books.Add(bookVM.Book);
            _DBContext.SaveChanges();
            TempData["Message"] = "Libro creado con éxito";

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var book = _DBContext.Books.Find(id);
            if (book == null) return NotFound();

            BookVM bookVM = new()
            {
                Book = book,
                AuthorList = GetAuthorList(book.AuthorId)
            };

            return View(bookVM);
        }

        [HttpPost]
        public IActionResult Edit(BookVM bookVM)
        {
            if (!ModelState.IsValid)
            {
                bookVM.AuthorList = GetAuthorList(bookVM.Book.AuthorId);
                return View(bookVM);
            }

            _DBContext.Books.Update(bookVM.Book);
            _DBContext.SaveChanges();
            TempData["Message"] = "Libro editado con éxito";

            return RedirectToAction("Index");
        }

        private List<SelectListItem> GetAuthorList(int? AuthorId = null)
        {
            return [.. _DBContext.Authors
                .Select(a => new SelectListItem
                {
                    Text = a.Name,
                    Value = a.Id.ToString(),
                    Selected = a.Id == AuthorId
                })];
        }

        public IActionResult Delete(int id)
        {
            var book = _DBContext.Books.Include(a => a.Author).Where(b => b.Id == id).FirstOrDefault();
            if (book == null) return NotFound();

            return View(book);
        }

        [HttpPost]
        public IActionResult Delete(Book book)
        {
            _DBContext.Books.Remove(book);
            _DBContext.SaveChanges();
            TempData["Message"] = "Libro eliminado con éxito";

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LIBRARYMVC</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LIBRARYMVC_TEST.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LIBRARYMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Autores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LIBRARYMVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>